In [8]:
import pandas as pd

df = pd.read_csv("customers-100.csv")
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [10]:
pivot = df.pivot_table(index='Country', values='Customer Id', aggfunc='count')
pivot = pivot.reset_index()
pivot.columns = ['Country', 'CustomerCount']  # Rename columns for clarity
pivot.head()

               Country  CustomerCount
0              Albania              1
1              Algeria              1
2             Anguilla              1
3  Antigua and Barbuda              1
4                Aruba              1

In [11]:
import plotly.express as px

fig = px.bar(pivot, x='Country', y=pivot.columns[1], title="Customers by Country")
fig.show()

In [12]:
print(df.columns)

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

## Sample Dashboard Layout

- Pivot Table: Customer Count by Country
- Plotly Bar Chart: Interactive view of customers
- Filters (optional): By Region, Age Group, or Spending
- Future Add-ons: Map visual, Trend line, Customer segment breakdown